[package]
name = "boxunbox"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.24", features = ["derive", "cargo", "unicode"] }
directories-next = "2.0.0"
path-clean = "1.0.1"
regex = "1.11.1"
ron = "0.8.1"
serde = { version = "1.0.217", features = ["derive"] }
shellexpand = "3.1.0"
