[workspace]
resolver = "3"
members = ["boxunbox"]
exclude = ["aur/*", "demo/*", "*.sh"]

[profile.dev]
opt-level = 0
debug = true
panic = "abort"

[profile.test]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
strip = "debuginfo"
lto = true
codegen-units = 1
panic = "abort"
