[package]
name = "boxunbox"
version = "0.1.11"
edition = "2024"

[[bin]]
name = "unbox"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.96"
clap = { version = "4.5.31", features = ["derive", "cargo", "unicode"] }
const_format = { version = "0.2.34", features = ["fmt"] }
directories-next = "2.0.0"
path-clean = "1.0.1"
pathdiff = "0.2.3"
regex = "1.11.1"
ron = "0.8.1"
serde = { version = "1.0.218", features = ["derive"] }
serde_regex = "1.1.0"
shellexpand = "3.1.0"
thiserror = "2.0.11"
walkdir = "2.5.0"
